CREATE TABLE IF NOT EXISTS public.nodo_weekly_recurring_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id bigint NOT NULL REFERENCES public.accounts(id) ON DELETE CASCADE,
  inbox_id bigint NOT NULL REFERENCES public.inboxes(id) ON DELETE CASCADE,
  conversation_id bigint NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
  conversation_display_id bigint NOT NULL,
  content text NOT NULL CHECK (char_length(content) BETWEEN 1 AND 4000),
  weekday smallint NOT NULL CHECK (weekday BETWEEN 0 AND 6),
  local_time time without time zone NOT NULL,
  timezone text NOT NULL DEFAULT 'Europe/Madrid',
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused', 'cancelled')),
  next_run_at timestamptz NOT NULL,
  last_materialized_at timestamptz,
  created_by_user_id bigint,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_nodo_weekly_recurring_due
  ON public.nodo_weekly_recurring_messages (next_run_at)
  WHERE status = 'active';

CREATE INDEX IF NOT EXISTS idx_nodo_weekly_recurring_conversation
  ON public.nodo_weekly_recurring_messages (account_id, conversation_display_id, status);

CREATE UNIQUE INDEX IF NOT EXISTS idx_nodo_scheduled_messages_recurring_occurrence
  ON public.nodo_scheduled_messages ((metadata ->> 'recurring_id'), send_at)
  WHERE metadata ? 'recurring_id';

ALTER TABLE public.nodo_weekly_recurring_messages ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.nodo_weekly_recurring_messages FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.nodo_weekly_recurring_messages_id_seq FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.nodo_weekly_recurring_messages TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.nodo_weekly_recurring_messages_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.nodo_next_weekly_occurrence(
  p_weekday integer,
  p_local_time time without time zone,
  p_timezone text,
  p_after timestamptz DEFAULT now()
) RETURNS timestamptz
LANGUAGE plpgsql
STABLE
SET search_path = public, pg_temp
AS $$
DECLARE
  local_date date;
  days_ahead integer;
  candidate timestamptz;
BEGIN
  IF p_weekday NOT BETWEEN 0 AND 6 THEN
    RAISE EXCEPTION 'weekday must be between 0 and 6';
  END IF;
  IF p_timezone <> 'Europe/Madrid' THEN
    RAISE EXCEPTION 'unsupported timezone';
  END IF;

  local_date := (p_after AT TIME ZONE p_timezone)::date;
  days_ahead := (p_weekday - EXTRACT(DOW FROM local_date)::integer + 7) % 7;
  candidate := ((local_date + days_ahead) + p_local_time) AT TIME ZONE p_timezone;

  IF candidate <= p_after + interval '30 seconds' THEN
    candidate := ((local_date + days_ahead + 7) + p_local_time) AT TIME ZONE p_timezone;
  END IF;

  RETURN candidate;
END;
$$;

CREATE OR REPLACE FUNCTION public.nodo_create_weekly_recurring_message(
  p_account_id bigint,
  p_conversation_display_id bigint,
  p_content text,
  p_weekday integer,
  p_local_time time without time zone,
  p_timezone text DEFAULT 'Europe/Madrid',
  p_user_id bigint DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  conv public.conversations%ROWTYPE;
  inbox_channel_type text;
  created public.nodo_weekly_recurring_messages%ROWTYPE;
BEGIN
  IF p_account_id NOT IN (1, 25) THEN RAISE EXCEPTION 'account not authorized'; END IF;
  IF p_content IS NULL OR char_length(trim(p_content)) NOT BETWEEN 1 AND 4000 THEN
    RAISE EXCEPTION 'content must contain between 1 and 4000 characters';
  END IF;
  IF p_weekday NOT BETWEEN 0 AND 6 THEN RAISE EXCEPTION 'weekday must be between 0 and 6'; END IF;
  IF p_timezone <> 'Europe/Madrid' THEN RAISE EXCEPTION 'unsupported timezone'; END IF;

  SELECT * INTO conv
  FROM public.conversations
  WHERE account_id = p_account_id AND display_id = p_conversation_display_id
  LIMIT 1;
  IF NOT FOUND THEN RAISE EXCEPTION 'conversation not found'; END IF;

  SELECT channel_type INTO inbox_channel_type FROM public.inboxes WHERE id = conv.inbox_id;
  IF inbox_channel_type <> 'Channel::Api' THEN
    RAISE EXCEPTION 'recurring messages require a Channel::Api inbox';
  END IF;

  INSERT INTO public.nodo_weekly_recurring_messages (
    account_id, inbox_id, conversation_id, conversation_display_id, content,
    weekday, local_time, timezone, next_run_at, created_by_user_id
  ) VALUES (
    p_account_id, conv.inbox_id, conv.id, conv.display_id, trim(p_content),
    p_weekday, p_local_time, p_timezone,
    public.nodo_next_weekly_occurrence(p_weekday, p_local_time, p_timezone, now()),
    p_user_id
  ) RETURNING * INTO created;

  RETURN to_jsonb(created);
END;
$$;

CREATE OR REPLACE FUNCTION public.nodo_list_weekly_recurring_messages(
  p_account_id bigint,
  p_conversation_display_id bigint
) RETURNS jsonb
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT COALESCE(jsonb_agg(to_jsonb(r) ORDER BY r.id DESC), '[]'::jsonb)
  FROM public.nodo_weekly_recurring_messages r
  WHERE r.account_id = p_account_id
    AND r.conversation_display_id = p_conversation_display_id;
$$;

CREATE OR REPLACE FUNCTION public.nodo_set_weekly_recurring_status(
  p_account_id bigint,
  p_conversation_display_id bigint,
  p_recurring_id bigint,
  p_status text
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  changed public.nodo_weekly_recurring_messages%ROWTYPE;
BEGIN
  IF p_status NOT IN ('active', 'paused', 'cancelled') THEN RAISE EXCEPTION 'invalid status'; END IF;

  UPDATE public.nodo_weekly_recurring_messages
  SET status = p_status,
      next_run_at = CASE
        WHEN p_status = 'active' THEN public.nodo_next_weekly_occurrence(weekday, local_time, timezone, now())
        ELSE next_run_at
      END,
      updated_at = now()
  WHERE id = p_recurring_id
    AND account_id = p_account_id
    AND conversation_display_id = p_conversation_display_id
    AND status <> 'cancelled'
  RETURNING * INTO changed;

  IF NOT FOUND THEN RAISE EXCEPTION 'recurring rule not found or already cancelled'; END IF;
  RETURN to_jsonb(changed);
END;
$$;

CREATE OR REPLACE FUNCTION public.nodo_update_weekly_recurring_message(
  p_account_id bigint,
  p_conversation_display_id bigint,
  p_recurring_id bigint,
  p_content text DEFAULT NULL,
  p_weekday integer DEFAULT NULL,
  p_local_time time without time zone DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  changed public.nodo_weekly_recurring_messages%ROWTYPE;
BEGIN
  IF p_content IS NOT NULL AND char_length(trim(p_content)) NOT BETWEEN 1 AND 4000 THEN
    RAISE EXCEPTION 'content must contain between 1 and 4000 characters';
  END IF;
  IF p_weekday IS NOT NULL AND p_weekday NOT BETWEEN 0 AND 6 THEN
    RAISE EXCEPTION 'weekday must be between 0 and 6';
  END IF;

  UPDATE public.nodo_weekly_recurring_messages
  SET content = COALESCE(NULLIF(trim(p_content), ''), content),
      weekday = COALESCE(p_weekday, weekday),
      local_time = COALESCE(p_local_time, local_time),
      next_run_at = public.nodo_next_weekly_occurrence(
        COALESCE(p_weekday, weekday), COALESCE(p_local_time, local_time), timezone, now()
      ),
      updated_at = now()
  WHERE id = p_recurring_id
    AND account_id = p_account_id
    AND conversation_display_id = p_conversation_display_id
    AND status <> 'cancelled'
  RETURNING * INTO changed;

  IF NOT FOUND THEN RAISE EXCEPTION 'recurring rule not found or cancelled'; END IF;
  RETURN to_jsonb(changed);
END;
$$;

CREATE OR REPLACE FUNCTION public.nodo_materialize_weekly_recurring_messages()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  recurring public.nodo_weekly_recurring_messages%ROWTYPE;
  materialized integer := 0;
BEGIN
  FOR recurring IN
    SELECT *
    FROM public.nodo_weekly_recurring_messages
    WHERE status = 'active' AND next_run_at <= now()
    ORDER BY next_run_at
    FOR UPDATE SKIP LOCKED
  LOOP
    INSERT INTO public.nodo_scheduled_messages (
      account_id, inbox_id, conversation_id, conversation_display_id,
      content, send_at, status, scheduled_by_user_id, scheduled_via, metadata,
      created_at, updated_at
    ) VALUES (
      recurring.account_id, recurring.inbox_id, recurring.conversation_id,
      recurring.conversation_display_id, recurring.content, recurring.next_run_at,
      'pending', recurring.created_by_user_id, 'recurring',
      jsonb_build_object(
        'recurring_id', recurring.id,
        'timezone', recurring.timezone,
        'weekday', recurring.weekday,
        'local_time', to_char(recurring.local_time, 'HH24:MI')
      ), now(), now()
    ) ON CONFLICT DO NOTHING;

    UPDATE public.nodo_weekly_recurring_messages
    SET last_materialized_at = recurring.next_run_at,
        next_run_at = public.nodo_next_weekly_occurrence(
          recurring.weekday, recurring.local_time, recurring.timezone,
          recurring.next_run_at + interval '1 second'
        ),
        updated_at = now()
    WHERE id = recurring.id;

    materialized := materialized + 1;
  END LOOP;

  RETURN materialized;
END;
$$;

REVOKE ALL ON FUNCTION public.nodo_create_weekly_recurring_message(bigint,bigint,text,integer,time without time zone,text,bigint) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.nodo_next_weekly_occurrence(integer,time without time zone,text,timestamp with time zone) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.nodo_list_weekly_recurring_messages(bigint,bigint) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.nodo_set_weekly_recurring_status(bigint,bigint,bigint,text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.nodo_update_weekly_recurring_message(bigint,bigint,bigint,text,integer,time without time zone) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.nodo_materialize_weekly_recurring_messages() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.nodo_create_weekly_recurring_message(bigint,bigint,text,integer,time without time zone,text,bigint) TO service_role;
GRANT EXECUTE ON FUNCTION public.nodo_next_weekly_occurrence(integer,time without time zone,text,timestamp with time zone) TO service_role;
GRANT EXECUTE ON FUNCTION public.nodo_list_weekly_recurring_messages(bigint,bigint) TO service_role;
GRANT EXECUTE ON FUNCTION public.nodo_set_weekly_recurring_status(bigint,bigint,bigint,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.nodo_update_weekly_recurring_message(bigint,bigint,bigint,text,integer,time without time zone) TO service_role;

SELECT cron.schedule(
  'nodo-materialize-weekly-recurring-messages',
  '* * * * *',
  'SELECT public.nodo_materialize_weekly_recurring_messages();'
);
